// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface _CameraOperations extends _DeviceOperations
{
    CameraStatePrx turnLeft(float angle, Ice.Current __current);

    CameraStatePrx turnRight(float angle, Ice.Current __current);

    CameraStatePrx turnUp(float angle, Ice.Current __current);

    CameraStatePrx turnDown(float angle, Ice.Current __current);
}
