// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface _LaboratoryRoomOperationsNC
{
    String[] getDevicesNamesList();

    String[] getDeviceOperationsList(String deviceId)
        throws NotKnownDeviceException;

    DevicePrx takeControlOverDevice(String deviceId, String userId)
        throws AlreadyControlledException,
               NotKnownDeviceException;

    void releaseDevice(String deviceId, String userId)
        throws DeviceNotControlledException,
               NotKnownDeviceException;
}
