// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class AlreadyControlledException extends Ice.UserException
{
    public AlreadyControlledException()
    {
        byWho = "";
    }

    public AlreadyControlledException(Throwable __cause)
    {
        super(__cause);
        byWho = "";
    }

    public AlreadyControlledException(String byWho)
    {
        this.byWho = byWho;
    }

    public AlreadyControlledException(String byWho, Throwable __cause)
    {
        super(__cause);
        this.byWho = byWho;
    }

    public String
    ice_name()
    {
        return "Demo::AlreadyControlledException";
    }

    public String byWho;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::Demo::AlreadyControlledException", -1, true);
        __os.writeString(byWho);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        byWho = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = -861474081L;
}
