// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public abstract class AsciiPrinterState extends PrinterState
                                        implements _AsciiPrinterStateOperations,
                                                   _AsciiPrinterStateOperationsNC
{
    public AsciiPrinterState()
    {
        super();
        prettyResult = "";
    }

    public AsciiPrinterState(float batteryLevel, String lastUserName, long operationTime, int inkLevel, String result, String prettyResult)
    {
        super(batteryLevel, lastUserName, operationTime, inkLevel, result);
        this.prettyResult = prettyResult;
    }

    public static final String[] __ids =
    {
        "::Demo::AsciiPrinterState",
        "::Demo::DeviceState",
        "::Demo::PrinterState",
        "::Ice::Object"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[0];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[0];
    }

    public static String ice_staticId()
    {
        return __ids[0];
    }

    private final static String[] __all =
    {
        "formatToString",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return DeviceState.___formatToString(this, in, __current);
            }
            case 1:
            {
                return ___ice_id(this, in, __current);
            }
            case 2:
            {
                return ___ice_ids(this, in, __current);
            }
            case 3:
            {
                return ___ice_isA(this, in, __current);
            }
            case 4:
            {
                return ___ice_ping(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeString(prettyResult);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        prettyResult = __is.readString();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public String prettyResult;

    public AsciiPrinterState
    clone()
    {
        return (AsciiPrinterState)super.clone();
    }

    public static final long serialVersionUID = 2099471856L;
}
