// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class BodyTemperatureState extends SensorState
{
    public BodyTemperatureState()
    {
        super();
        temperatureColor = diodecolor.RED;
    }

    public BodyTemperatureState(float batteryLevel, String lastUserName, long operationTime, float speedInMilesPerHour, float speedInMetresPerHour, diodecolor speedColor, float temperatureInCentimeters, float temperatureInFahrenheits, diodecolor temperatureColor)
    {
        super(batteryLevel, lastUserName, operationTime, speedInMilesPerHour, speedInMetresPerHour, speedColor);
        this.temperatureInCentimeters = temperatureInCentimeters;
        this.temperatureInFahrenheits = temperatureInFahrenheits;
        this.temperatureColor = temperatureColor;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new BodyTemperatureState();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Demo::BodyTemperatureState",
        "::Demo::DeviceState",
        "::Demo::SensorState",
        "::Ice::Object"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[0];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[0];
    }

    public static String ice_staticId()
    {
        return __ids[0];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeFloat(temperatureInCentimeters);
        __os.writeFloat(temperatureInFahrenheits);
        diodecolor.__write(__os, temperatureColor);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        temperatureInCentimeters = __is.readFloat();
        temperatureInFahrenheits = __is.readFloat();
        temperatureColor = diodecolor.__read(__is);
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public float temperatureInCentimeters;

    public float temperatureInFahrenheits;

    public diodecolor temperatureColor;

    public BodyTemperatureState
    clone()
    {
        return (BodyTemperatureState)super.clone();
    }

    public static final long serialVersionUID = -1229639339L;
}
