// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class BrokenDiodeException extends Ice.UserException
{
    public BrokenDiodeException()
    {
        reason = "";
    }

    public BrokenDiodeException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public BrokenDiodeException(float maxMeasuredValue, float actualMeasuredValue, String reason)
    {
        this.maxMeasuredValue = maxMeasuredValue;
        this.actualMeasuredValue = actualMeasuredValue;
        this.reason = reason;
    }

    public BrokenDiodeException(float maxMeasuredValue, float actualMeasuredValue, String reason, Throwable __cause)
    {
        super(__cause);
        this.maxMeasuredValue = maxMeasuredValue;
        this.actualMeasuredValue = actualMeasuredValue;
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "Demo::BrokenDiodeException";
    }

    public float maxMeasuredValue;

    public float actualMeasuredValue;

    public String reason;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::Demo::BrokenDiodeException", -1, true);
        __os.writeFloat(maxMeasuredValue);
        __os.writeFloat(actualMeasuredValue);
        __os.writeString(reason);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        maxMeasuredValue = __is.readFloat();
        actualMeasuredValue = __is.readFloat();
        reason = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = -315710470L;
}
