// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public abstract class CameraState extends DeviceState
                                  implements _CameraStateOperations,
                                             _CameraStateOperationsNC
{
    public CameraState()
    {
        super();
    }

    public CameraState(float batteryLevel, String lastUserName, long operationTime, float horizontalAngle, float verticalAngle)
    {
        super(batteryLevel, lastUserName, operationTime);
        this.horizontalAngle = horizontalAngle;
        this.verticalAngle = verticalAngle;
    }

    public static final String[] __ids =
    {
        "::Demo::CameraState",
        "::Demo::DeviceState",
        "::Ice::Object"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[0];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[0];
    }

    public static String ice_staticId()
    {
        return __ids[0];
    }

    private final static String[] __all =
    {
        "formatToString",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    public Ice.DispatchStatus __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return DeviceState.___formatToString(this, in, __current);
            }
            case 1:
            {
                return ___ice_id(this, in, __current);
            }
            case 2:
            {
                return ___ice_ids(this, in, __current);
            }
            case 3:
            {
                return ___ice_isA(this, in, __current);
            }
            case 4:
            {
                return ___ice_ping(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeFloat(horizontalAngle);
        __os.writeFloat(verticalAngle);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        horizontalAngle = __is.readFloat();
        verticalAngle = __is.readFloat();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public float horizontalAngle;

    public float verticalAngle;

    public CameraState
    clone()
    {
        return (CameraState)super.clone();
    }

    public static final long serialVersionUID = 348240220L;
}
