// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface DeviceLister extends Ice.Object,
                                      _DeviceListerOperations, _DeviceListerOperationsNC
{
    public static final String ice_staticId = "::Demo::DeviceLister";

    public static final long serialVersionUID = -598785133L;
}
