// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface LaboratoryRoomPrx extends Ice.ObjectPrx
{
    public String[] getDevicesNamesList();

    public String[] getDevicesNamesList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDevicesNamesList();

    public Ice.AsyncResult begin_getDevicesNamesList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getDevicesNamesList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getDevicesNamesList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getDevicesNamesList(Callback_LaboratoryRoom_getDevicesNamesList __cb);

    public Ice.AsyncResult begin_getDevicesNamesList(java.util.Map<String, String> __ctx, Callback_LaboratoryRoom_getDevicesNamesList __cb);

    public Ice.AsyncResult begin_getDevicesNamesList(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDevicesNamesList(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getDevicesNamesList(java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getDevicesNamesList(java.util.Map<String, String> __ctx, 
                                                     IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_getDevicesNamesList(Ice.AsyncResult __result);
}
