// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public final class MoistureSensorHolder extends Ice.ObjectHolderBase<MoistureSensor>
{
    public
    MoistureSensorHolder()
    {
    }

    public
    MoistureSensorHolder(MoistureSensor value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof MoistureSensor)
        {
            value = (MoistureSensor)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _MoistureSensorDisp.ice_staticId();
    }
}
