// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class NotKnownDeviceException extends Ice.UserException
{
    public NotKnownDeviceException()
    {
        explanation = "";
    }

    public NotKnownDeviceException(Throwable __cause)
    {
        super(__cause);
        explanation = "";
    }

    public NotKnownDeviceException(String explanation)
    {
        this.explanation = explanation;
    }

    public NotKnownDeviceException(String explanation, Throwable __cause)
    {
        super(__cause);
        this.explanation = explanation;
    }

    public String
    ice_name()
    {
        return "Demo::NotKnownDeviceException";
    }

    public String explanation;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::Demo::NotKnownDeviceException", -1, true);
        __os.writeString(explanation);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        explanation = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 190522485L;
}
