// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class OutOfInkException extends Ice.UserException
{
    public OutOfInkException()
    {
        reason = "";
    }

    public OutOfInkException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public OutOfInkException(int actualInkLvl, int requiredInkLvl, String reason)
    {
        this.actualInkLvl = actualInkLvl;
        this.requiredInkLvl = requiredInkLvl;
        this.reason = reason;
    }

    public OutOfInkException(int actualInkLvl, int requiredInkLvl, String reason, Throwable __cause)
    {
        super(__cause);
        this.actualInkLvl = actualInkLvl;
        this.requiredInkLvl = requiredInkLvl;
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "Demo::OutOfInkException";
    }

    public int actualInkLvl;

    public int requiredInkLvl;

    public String reason;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::Demo::OutOfInkException", -1, true);
        __os.writeInt(actualInkLvl);
        __os.writeInt(requiredInkLvl);
        __os.writeString(reason);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        actualInkLvl = __is.readInt();
        requiredInkLvl = __is.readInt();
        reason = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = 1525448144L;
}
