// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface SensorPrx extends DevicePrx
{
    public SensorStatePrx measureMotion(speed speedObj);

    public SensorStatePrx measureMotion(speed speedObj, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_measureMotion(speed speedObj);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, Ice.Callback __cb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, Callback_Sensor_measureMotion __cb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, java.util.Map<String, String> __ctx, Callback_Sensor_measureMotion __cb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, 
                                               IceInternal.Functional_GenericCallback1<SensorStatePrx> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, 
                                               IceInternal.Functional_GenericCallback1<SensorStatePrx> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<SensorStatePrx> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_measureMotion(speed speedObj, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<SensorStatePrx> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public SensorStatePrx end_measureMotion(Ice.AsyncResult __result);
}
