// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class ZoomingCameraState extends CameraState
{
    public ZoomingCameraState()
    {
        super();
    }

    public ZoomingCameraState(float batteryLevel, String lastUserName, long operationTime, float horizontalAngle, float verticalAngle, int zoomLvl)
    {
        super(batteryLevel, lastUserName, operationTime, horizontalAngle, verticalAngle);
        this.zoomLvl = zoomLvl;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new ZoomingCameraState();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Demo::CameraState",
        "::Demo::DeviceState",
        "::Demo::ZoomingCameraState",
        "::Ice::Object"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[2];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[2];
    }

    public static String ice_staticId()
    {
        return __ids[2];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeInt(zoomLvl);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        zoomLvl = __is.readInt();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public int zoomLvl;

    public ZoomingCameraState
    clone()
    {
        return (ZoomingCameraState)super.clone();
    }

    public static final long serialVersionUID = 1509424064L;
}
