// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `laboratory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ZoomingCameraPrx extends CameraPrx
{
    public ZoomingCameraStatePrx zoom(int lvl);

    public ZoomingCameraStatePrx zoom(int lvl, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_zoom(int lvl);

    public Ice.AsyncResult begin_zoom(int lvl, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_zoom(int lvl, Ice.Callback __cb);

    public Ice.AsyncResult begin_zoom(int lvl, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_zoom(int lvl, Callback_ZoomingCamera_zoom __cb);

    public Ice.AsyncResult begin_zoom(int lvl, java.util.Map<String, String> __ctx, Callback_ZoomingCamera_zoom __cb);

    public Ice.AsyncResult begin_zoom(int lvl, 
                                      IceInternal.Functional_GenericCallback1<ZoomingCameraStatePrx> __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_zoom(int lvl, 
                                      IceInternal.Functional_GenericCallback1<ZoomingCameraStatePrx> __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_zoom(int lvl, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_GenericCallback1<ZoomingCameraStatePrx> __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_zoom(int lvl, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_GenericCallback1<ZoomingCameraStatePrx> __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public ZoomingCameraStatePrx end_zoom(Ice.AsyncResult __result);
}
